sass:
  style: compressed

#  Build settings
markdown: kramdown

gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
   
#  Site settings
title: VAL Annual Review 2015-2016
description: Helping people change their lives for the better
url: http://www.valonline.org.uk/2016
baseurl: /2016
email: helpline@valonline.org.uk
github: richardatval/annual-review-2016.valonline.org.uk
logo_path: /img/logo.svg
copyright: "Voluntary Action LeicesterShire is the trading name of Voluntary Action Leicester registered charity (No. 509300) Company Limited by Guarantee (No. 1357513) Registered in England and Wales. Copyright © 2016 Voluntary Action Leicester"

#  Features

googlecharts: false

#  Social media settings

facebook: "voluntaryactionleics"
twitter : "valonline"

permalink: pretty

analyticstracking: " "

paginate: 5
paginate_path: "/news/:num/"

#  Timezone
timezone: Europe/London

exclude: ['bower.json']

#  Configuration for prose.io online editor
prose:
  ignore: ['_includes','assets','_assets','_layouts','_plugins','/.jekyll-metadata','feed.xml','bin','js','css','_sass','_config.yml','bower.json']